// Generated by https://quicktype.io

export interface GistResponse {
  url: string
  forks_url: string
  commits_url: string
  id: string
  node_id: string
  git_pull_url: string
  git_push_url: string
  html_url: string
  files: {
    [key in string]: Files
  }
  public: boolean
  created_at: string
  updated_at: string
  description: string
  comments: number
  user: null
  comments_url: string
  owner: Owner
  forks: Fork[]
  history: History[]
  truncated: boolean
}

export interface Files {
  filename: string
  type: string
  language: string
  raw_url: string
  size: number
  truncated: boolean
  content: string
}

export interface Fork {
  url: string
  user: User
  id: string
  created_at: string
  updated_at: string
}

export interface User {
  login: string
  id: number
  node_id: string
  avatar_url: string
  gravatar_id: string
  url: string
  html_url: string
  followers_url: string
  following_url: string
  gists_url: string
  starred_url: string
  subscriptions_url: string
  organizations_url: string
  repos_url: string
  events_url: string
  received_events_url: string
  type: Type
  site_admin: boolean
  name: string
  company: string
  blog: string
  location: string
  email: null | string
  hireable: null
  bio: null
  twitter_username: string
  public_repos: number
  public_gists: number
  followers: number
  following: number
  created_at: string
  updated_at: string
}
export interface History {
  user: Owner
  version: string
  committed_at: string
  change_status: ChangeStatus
  url: string
}

export interface ChangeStatus {
  total: number
  additions: number
  deletions: number
}

export interface Owner {
  login: string
  id: number
  node_id: string
  avatar_url: string
  gravatar_id: string
  url: string
  html_url: string
  followers_url: string
  following_url: string
  gists_url: string
  starred_url: string
  subscriptions_url: string
  organizations_url: string
  repos_url: string
  events_url: string
  received_events_url: string
  type: string
  site_admin: boolean
}
